### ISSUE TITLE
Black background on login screen, cannot change

### ISSUE THREAD

**Issue by markuspfeiffer** [Antergos/lightdm-webkit2-greeter#31]
After the latest updates (including Gnome 3.20) the login screen no longer shows a background image but is a solid black color. This affects the background only, the login prompt is still shown and login works as normal.

The menu button on the top left can be used to select different backgrounds, but the background always stays a solid black. Clicking on a different background gives the fade-out/fade-in effect of the login prompt as if it was changing backgrounds.

**Comment by lots0logs** [comment]
Hi, could you provide [paste2](http://paste2.org) links of the following files:

* `/etc/lightdm/lightdm-webkit2-greeter.conf`
* `/var/log/lightdm/x-0-greeter.log`

**Comment by markuspfeiffer** [comment]
Sure thing.

`cat /etc/lightdm/lightdm-webkit2-greeter.conf`
http://paste2.org/XL63x7xA

`sudo cat /var/log/lightdm/x-0-greeter.log`
This file is empty.

**Comment by lots0logs** [comment]
Are you using Antergos or Arch? I just released v2.1.1. Please try it and let me know if the result is the same.

**Comment by markuspfeiffer** [comment]
I'm on Antergos. I'm at work right now, will try it once I get home.

**Comment by matt-snider** [comment]
Same issue here on fresh install after trying to also install and switch to the material theme.

**Comment by markuspfeiffer** [comment]
Upgrading to lightdm-webkit2-greeter version 2.1.1-1 did not solve the issue for me.

During the update I received the following console output:
```
 ==> NOTE: MANUAL ACTION REQUIRED! <==
  ** The greeter's config file contains important changes. It has been saved as
  ** /etc/lightdm/lightdm-webkit2-greeter.conf.pacnew. You must either merge the
  ** changes into /etc/lightdm/lightdm-webkit2-greeter.conf
  ** or replace the latter with the former.
```

However, there is no `lightdm-webkit2-greeter.conf.pacnew` file.

**Comment by lots0logs** [comment]
@matt-snider Does the default theme work properly? Themes must be updated with the latest API changes. You'll have to contact the theme developer regarding that.

**Comment by lots0logs** [comment]
@markuspfeiffer Could you try clearing the cached files and then if the issue persist check the logs for anything new.
```
rm ~/.cache/lightdm-webkit2-greeter
rm ~/.local/share/webkitgtk
sudo rm /var/cache/lightdm /var/cache/lightdm-webkit2-greeter
```

**Comment by markuspfeiffer** [comment]
I'm afraid removing the cache directories did nothing. Two of them did not exist.

```
rm: cannot remove '/home/markus/.cache/lightdm-webkit2-greeter': No such file or directory
rm: cannot remove '/var/cache/lightdm-webkit2-greeter': No such file or directory
```

The `x-0-greeter.log` and the `x-1-greeter.log` are still empty. I looked through the rest of the logs but there seem to be no errors regarding the greeter (one for a missing plymouth directory and one bug for KMS regarding axes).

**Comment by lots0logs** [comment]
@markuspfeiffer Could you try enabling debug mode in `/etc/lightdm/lightdm-webkit2-greeter.conf`, then restart so the greeter will load, and finally check the logs again.

**Comment by markuspfeiffer** [comment]
I just noticed something interesting. When I click on "Random" I do get a background image. Clicking on Random multiple times will change the background image every time. However, clicking on another image still does nothing. So click on random, get an image, click on another image get the fade-out/fade-in effect, but stay on the last random image.

Will enable the debug mode now.

**Comment by markuspfeiffer** [comment]
Enabled debug-mode, did a system reboot. Attempted to change image three times, clicked on random, then attempted to change the image three times again. Here's the log output:

```
CONSOLE LOG Last session for markus was: gnome
CONSOLE LOG Adding GNOME to the session list...
CONSOLE LOG Adding GNOME Classic to the session list...
CONSOLE LOG Adding GNOME on Wayland to the session list...
CONSOLE LOG Starting authentication for markus.
CONSOLE LOG Session for markus is gnome
CONSOLE LOG undefined
CONSOLE LOG undefined
```
All lines are prepended with `file:///usr/share/lightdm-webkit/themes/antergos/js/greeter.js:86:15:` (which is the console.log call).

**Comment by lots0logs** [comment]
hmm..okay, let me check a few places and see if I can identify the problem. I'll let you know something here shortly.

**Comment by lots0logs** [comment]
@markuspfeiffer Could you try completely removing and then reinstalling the greeter?
```
sudo pacman -Rdd lightdm-webkit2-greeter
# This shouldn't be installed but just in case it is...
sudo pacman -Rdd lightdm-webkit-theme-antergos
# Make sure there's no chance for leftover files
sudo rm -rf /usr/share/lightdm-webkit/themes/antergos
# Delete cached package so that pacman has to download a fresh copy.
cd /var/cache/pacman/pkg/ && rm lightdm-webkit***
# Reinstall
sudo pacman -Syyu lightdm-webkit2-greeter
# Make sure wallpapers directory has proper permissions
sudo chmod -R 644 /usr/share/antergos
sudo chmod 755 /usr/share/antergos
```

**Comment by markuspfeiffer** [comment]
I just updated the Antergos installation on my laptop at work, which lead to the same issue (e.g. black background). I don't really use that installation, so aside from installing Eclipse it should match a clean install.

I reinstalled the greeter as per your instructions, but the issue remains. I must've done something wrong the first time, because all the preview images were now gone as well. I repeated the steps and now I'm back to a black background (and Random still works).

**Comment by lots0logs** [comment]
@markuspfeiffer Okay, lets try something else. I built a copy of the greeter that will allow you to access the developer console from the login screen so you can let me know what errors you see. Here's how to do it:

1. Install the greeter with developer console enabled:

   ```
sudo pacman -U https://www.dropbox.com/s/s8r9j642xxfkolm/lightdm-webkit2-greeter-2.1.1-1.1-x86_64.pkg.tar?dl=1
   ```

2. Check to make sure debug mode is enabled in `/etc/lightdm/lightdm-webkit2-greeter.conf`
3. Restart your system.
4. From the login screen, right click (anywhere) and then click "Inspect Element".
5. Open the tab labeled "Console" in the developer console that appeared at the bottom of the screen.
6. Record any/all messages you see.

**Comment by markuspfeiffer** [comment]
Hm, that doesn't seem to work. Right clicking anywhere does nothing. Is there some keyboard shortcut I could try? I've double checked that `debug_mode = true` is set in my `/etc/lightdm/lightdm-webkit2-greeter.conf`. Anything else I might've missed?

The log file contains some additional output now. I've run the first line through a JSON formatter for readability, it's a single line in the actual log file.

```
CONSOLE LOG {
    "this.logo": "/usr/share/lightdm-webkit/themes/antergos/img/antergos.png",
    "this.debug": true,
    "this.user_image": "/usr/share/lightdm-webkit/themes/antergos/img/antergos-logo-user.png",
    "this.background_images": [
        "/usr/share/antergos/wallpapers/solely_by_stevenfields.jpg",
        "/usr/share/antergos/wallpapers/morning_light.jpg",
        "/usr/share/antergos/wallpapers/field_by_stevenfields-d59ap2i.jpg",
        "/usr/share/antergos/wallpapers/83II_by_bo0xVn.jpg",
        "/usr/share/antergos/wallpapers/as_time_goes_by____by_moskanon-d5dgvt8.jpg",
        "/usr/share/antergos/wallpapers/In_the_Grass.jpg",
        "/usr/share/antergos/wallpapers/blossom_by_snipes2.jpg",
        "/usr/share/antergos/wallpapers/white_line_by_snipes2.jpg",
        "/usr/share/antergos/wallpapers/c65sk3mshowxrtlljbvh.jpg",
        "/usr/share/antergos/wallpapers/autumn_hike___plant_details_by_aoiban-d5l7y83.jpg",
        "/usr/share/antergos/wallpapers/Grass_Fullscreen.jpg",
        "/usr/share/antergos/wallpapers/extinction_by_signcropstealer-d5j4y84.jpg",
        "/usr/share/antergos/wallpapers/antergos-wallpaper.png",
        "/usr/share/antergos/wallpapers/Nautilus_Fullscreen.jpg",
        "/usr/share/antergos/wallpapers/early_morning_by_kylekc.jpg",
        "/usr/share/antergos/wallpapers/Grass_by_masha_darkelf666.jpg",
        "/usr/share/antergos/wallpapers/the_world_inside_my_lens__by_moskanon-d5fsiqs.jpg",
        "/usr/share/antergos/wallpapers/humble_by_splendidofsun-d5g47hb.jpg",
        "/usr/share/antergos/wallpapers/sky_full_of_stars.jpg",
        "/usr/share/antergos/wallpapers/nikon_d40.jpg"
    ],
    "this.background_images_dir": "/usr/share/antergos/wallpapers"
}
CONSOLE LOG Last session for markus was: gnome
CONSOLE LOG Adding GNOME to the session list...
CONSOLE LOG Adding GNOME Classic to the session list...
CONSOLE LOG Adding GNOME on Wayland to the session list...
CONSOLE LOG Starting authentication for markus.
CONSOLE LOG Session for markus is gnome
CONSOLE LOG undefined
CONSOLE LOG undefined
```

**Comment by wojtekw86** [comment]
Yesterday I did an upgrade of my arch and new lightdm-webkit2-greeter stop working. Before upgrade I have used it with material theme and it was all ok. Now after upgrade there was only black screen only (without any login box or something). I was strugling with that all evening and end up removing lightdm-webkit2-greeter manually and reinstalling lightdm-webkit-greeter and now it all works fine again even with all new gui changes in material theme which has now officially lightdm-webkit2-greeter dependency instead lightdm-webkit-greeter like before (but not working that way).

**Comment by lots0logs** [comment]
I forgot to enable right-clicking :sweat_smile:  This one should let you access the dev console...
```
sudo pacman -U https://www.dropbox.com/s/van86aifl7mry80/lightdm-webkit2-greeter-2.1.1-1.2-x86_64.pkg.tar?dl=1
```

**Comment by wojtekw86** [comment]
Ahh.. and also antergos theme had problems with lightdm-webkit2-greeter, it displays gray background white login box with only antergos logo, and empty blue rounded rectangle in right upper corner. No input text boxes, no borders, no texts, no buttons, no nothing else and cannot login also. Maybe it is unrelated but after the same upgrade I noticed strange gui behaviour of firefox. Bookmark bar was displaying icons like there werent any spacings, margins or padding anywhere, also no spaces in context menu when left mouse clicking there, and no colour-marking text selection nor on any site nor on url input text field. Weird. Like something with gtk or some related packets were broken. I doubt firefox uses webkit and for sure not only in bookmark bar. Maybe this help.

**Comment by markuspfeiffer** [comment]
Yep, this one works.

No errors in the console, but a couple of warnings (8) about `Unexpected CSS token: :`
font-awesome.min.css:4:1607
font-awesome.min.css:4:1770
font-awesome.min.css:4:1936
font-awesome.min.css:4:2107
font-awesome.min.css:4:2280
bootstrap.min.css:617:171
bootstrap.min.css:1208:479
bootsrap.min.css:1209:502

They refer to lines such as:
```
.fa-rotate-270 {
  filter: progid: DXImageTransform.Microsoft.BasicImage(rotation=1);
  ...
}
```
Not sure if this is the issue?

**Comment by lots0logs** [comment]
I'm running out of ideas here. It really is not making sense at this point. Everything appears to be loading fine concerning the backgrounds from what you have in the logging output. What is your system's locale set to?

**Comment by markuspfeiffer** [comment]
It's also weird that the Random button lets me change backgrounds (well, randomly), but the individual buttons do not.

Here's the output of `locale`:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by Davidmp1** [comment]
Hello. Yesterday I had the same problem while upgrading to Gnome 3.20. When it rebooted, lightdm-webkit2-greeter showed a black background, a black window at the centre with no login prompt, just an Antergos title at the left upper corner and a small arrow at the middle. Clicking the arrow only moved it upwards and clicking it again moved it back. I did not find a way to login writing the password where it should be or trying to login using only the keyboard: hit enter and write the password. On the right upper end there was a box for changing the background that if clicked showed nothing except the box corresponding to the random mode. No images anywhere. Using Ctrl+Alt+F2, I switched to GDM (which I had installed since the last issue with lightdm, the blank screen) and I could login with no problem. I have not uninstalled lightdm.
During the update I also had this message:

 ==> NOTE: MANUAL ACTION REQUIRED! <==
  ** The greeter's config file contains important changes. It has been saved as
  ** /etc/lightdm/lightdm-webkit2-greeter.conf.pacnew. You must either merge the
  ** changes into /etc/lightdm/lightdm-webkit2-greeter.conf
  ** or replace the latter with the former.
I have both files but I don't know how to merge them or what should be merged. I have not yet tried to switch back to the former.
Here you have my lightdm config files:
[conf_files.zip](https://github.com/Antergos/lightdm-webkit2-greeter/files/216821/conf_files.zip)

**Comment by lots0logs** [comment]
@Davidmp1 If you havent customized the config file you can simply replace the old file with the new file and it will work properly for you :smile:

**Comment by markuspfeiffer** [comment]
I just did a fresh install of Antergos inside VirtualBox, using the antergos-2016.03.20-x86_64.iso. This virtual machine shows exactly the same behavior as my real machine (black background unless Random is used).

If it would be of any help, I can export the machine and make it available to you?

**Comment by really-need-an-api-key** [comment]
Also experiencing this issue after updating to 3.20, logs don't show anything different from what was pasted here either.

**Comment by lots0logs** [comment]
@markuspfeiffer Yes please. That would help.

**Comment by markuspfeiffer** [comment]
Here you go: https://dl.dropboxusercontent.com/u/60400833/Antergos.ova

This is a virtual machine created with VirtualBox 5.0.16_OSE r105871 and exported as an OVA, using OVF 2.0. You should be able to import it back into VirtualBox using File > Import Appliance. Username and password for the machine are `antergos`.

**Comment by Davidmp1** [comment]
So, just to be even more clear and helpful for anyone else reading this...
The thing to do after the upgrade is to save /etc/lightdm/lightdm-webkit2-greeter.conf with a different name, just to save a copy of the old file, and just rename /etc/lightdm/lightdm-webkit2-greeter.conf.pacnew to /etc/lightdm/lightdm-webkit2-greeter.conf or make sure the contents of /etc/lightdm/lightdm-webkit2-greeter.conf.pacnew are the same in /etc/lightdm/lightdm-webkit2-greeter.conf. (If necessary, then, customize it again as needed.)
Is this ok? Thanks for your attention.

**Comment by mpfeiffermway** [comment]
As I pointed out here: https://github.com/Antergos/lightdm-webkit2-greeter/issues/31#issuecomment-208466607 there is no such file. Otherwise I would've done that.

**Comment by markuspfeiffer** [comment]
@Davidmp1 Also, as I pointed out in https://github.com/Antergos/lightdm-webkit2-greeter/issues/31#issuecomment-209575421, this issue also affects fresh installations of Antergos. Not sure how a person who just did a fresh install is supposed to figure out they need to copy a nonexistent configuration file over another.

**Comment by Davidmp1** [comment]
@markuspfeiffer, I was not replying any of your comments because your situation is different, I was just trying to clarify what @lots0logs had said to me to be sure of understanding it correctly. Sorry if you thought I was answering you... 
But, by the way, I have posted my configuration files and maybe you could use them... Be aware that I have added a line to change the default screen resolution. 
If this happens with a fresh installation this really blows away any expectations a new user might have and it should be adressed seriously and warned accordingly. For what I know a fresh installation of Antergos is more like a net installation and maybe the upgrade script (if there is any, I don't know) that saves the new configuration in lightdm-webkit2-greeter.conf.pacnew doesn't get triggered because there is nothig previous to upgrade and it simply installs the new configuration in lightdm-webkit2-greeter.conf... And if this doesn't work well, the new contents of the file won't either. I will know when I try it tomorrow...

**Comment by markuspfeiffer** [comment]
@Davidmp1 Sorry about that, I misinterpreted your comment :) Thank's I'll definitely try with your configuration file. As mentioned above, I did notice that I was supposed to replace the file, but there was no .pacnew file to be found on my computer :( My old configuration file wasn't customized either.

To my understanding a fresh install will use the packages from the .iso unless there's a newer file on the server. I did try to do an offline install (to get the old version) and then upgrade it (to simulate the upgrade issue), but that's not possible (must be online to install).

But in my test with a VM the issue also showed up with a fresh installation. So that should probably be fixed :)

**Comment by lots0logs** [comment]
@markuspfeiffer Still have not had a chance to check the VM but I have imported it into vbox already so I will get to it asap. 

There are two separate issues being discussed here and it is starting to cause confusion. The first issue is simply that the background switcher doesn't work and no background appears (so its just black). The login screen is otherwise fully functional. 

Some of you are reporting a more serious issue where the login screen is not at all functional. That needs to be moved into a separate github issue so we can avoid further confusion. It doesnt matter who creates the new issue, so whoever can get to it first please feel free to do it. Thanks!

**Comment by lots0logs** [comment]
@markuspfeiffer Please let me know if the issue is resolved with the latest version of the greeter (2.1.3).

**Comment by markuspfeiffer** [comment]
I'm not at home over the weekend, so I won't have a chance to test until Sunday night/Monday morning. Hope that's ok :)
On Apr 16, 2016 08:40, Dustin Falgout <notifications@github.com> wrote:@markuspfeiffer Please let me know if the issue is resolved with the latest version of the greeter (2.1.3).

**Comment by markuspfeiffer** [comment]
Unfortunately the update to 2.1.3-1 did not solve the issue for me. It did contain a .pacnew, which I used to replace my existing configuration. The only change is the addition of the `screensaver-timeout` value.

Random still shows a background. Choosing a different value is no longer saved and will switch back to Random on reboot. So I do get a (random) background on every boot now, instead of black. I can still force the black background in debug mode, by using the reload button.

Here's the [x-0-greeter.log](http://paste2.org/jckY12jW) I get when I log in with a random background.

Here's the [x-0-greeter.log](http://paste2.org/U0yB5OyH) I get when I log in after manually selecting a background and doing a reload.

Aside from one `undefined` entry, the log now contains the following error messages:
```
(lightdm-webkit2-greeter:533): Gtk-WARNING **: Allocating size to WebKitWebViewBase 0x2990360 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
```
file:///usr/share/lightdm-webkit/themes/antergos/js/greeter.js:114:15: CONSOLE LOG cache_set() called with key: ant:user:markus:session and value: undefined
undefined: CONSOLE ERROR Expected a string
```

**Comment by lots0logs** [comment]
@markuspfeiffer It turns out that this is an upstream regression in webkitgtk. I submitted a patch for it which should land in the package for the next minor point release (2.12.2)

**Comment by markuspfeiffer** [comment]
@lots0logs Thank you for the info and all your help :) Should we close this issue or do you want to keep it open until the patched version if webkitgtk has been released?
